### ISSUE TITLE
nbiff can't be killed gracefully

### ISSUE THREAD

**Issue by noarchwastaken** [pablo-blueoakdb/nbiff#1]
I was trying to mash up a shell script that runs nbiff when Thunderbird starts, and let nbiff exit when Thunderbird exits:

```sh
~/.nbiff/systray/Run_nbiff nbiff_qt5.py & pid1=$! && thunderbird; kill $pid1
```

This should ideally kill nbiff when thunderbird exits (as it works for most programs); however, the systray still hangs around.

So I have to kill the process group:

```sh
~/.nbiff/systray/Run_nbiff nbiff_qt5.py & pid1=$! && thunderbird; pkill -P $pid1
```

But I don't know if I'm missing some cleanup routine by doing so.

Would you please provide an easy way to kill nbiff gracefully, or to run/exit nbiff alongside Thunderbird instead of starting with the DE?

**Comment by pablos-here** [comment]
Hi,

I like your idea better than setting up a DE task.

I'll write a properly working wrapper script.

**Comment by pablos-here** [comment]
Thank you for reporting the issue (I should have mentioned that first ... ;) 

Please see snarf the latest drop and upgrade:

```shell
./Install_latest.tbird # to upgrade the latest bits
~/src/nbiff/src/systray/Run_tbird_nbiff # the new wrapper script
```
If all looks good, please close the issue.

**Comment by noarchwastaken** [comment]
Thank you very much! For a sway user like me, nbiff worked as well as birdtray (it's a tiling WM, no need to worry about window hiding), but is way simpler. Will definitely continue using.
