### ISSUE TITLE
Troubleshooting Preview Changes link doesn't work

### ISSUE THREAD

**Issue by craigs100** [pablo-blueoakdb/nbiff#3]
In Troubleshooting.md the "Preview Changes" link doesn't work at the start of the "Where to begin" section. (So I couldn't start, lol)

Installed in Linux Mint 20.2 Cinnamon with TB 78.14.0 and it doesn't work for me, hence looking at Troubleshooting.

Have been desperate for something like this for years.

**Comment by pablos-here** [comment]
Ouch.  Thank you for reporting the link bug.  I'll fix that first and after, we can sort out the issue you're facing.  

Are you on Reddit, if so, we can use it for troubleshooting?  If not, we can open a new ticket and track it here.

**Comment by pablos-here** [comment]
Link fixed!  Thanks again!
