### ISSUE TITLE
KDE support?

### ISSUE THREAD

**Issue by mercifulboss** [pablo-blueoakdb/nbiff#5]
I have been trying to use nbiff with Plasma 6 Wayland and it seems to launch and count show the correct number of messages on KDE Plasma but when I close thunderbird nbiff closes as well.

Here is the error message I see in the terminal:
![image](https://github.com/pablos-here/nbiff/assets/90151527/4909d2fe-5b27-42cc-8b64-99090b49b04e)

How to make this work properly? Thank you!

**Comment by pablos-here** [comment]
Hi,
To ensure I understand correctly, when you exit Thunderbird, nbiff exits too?  Is that what you mean?  If so, that's the design of `nibiff`.

The error cited has nothing to do with `nbiff`, it does not use Javascript.  

Thx!

**Comment by pablos-here** [comment]
Please re-open if I have misunderstood the issue.  Thx!

**Comment by mercifulboss** [comment]
> Hi, To ensure I understand correctly, when you exit Thunderbird, nbiff exits too? Is that what you mean? If so, that's the design of `nibiff`.
> 
> The error cited has nothing to do with `nbiff`, it does not use Javascript.
> 
> Thx!

Apologies, thought I replied. I meant that I thought the point of nbiff was to create a tray that Thunderbird will close to when you close thunderbird (and so you can recieve messages and keep it in tray).

**Comment by pablos-here** [comment]
> I meant that I thought the point of nbiff was to create a tray that Thunderbird will close to when you close thunderbird (and so you can recieve messages and keep it in tray).

If you don't want to see `Thunderbird` in the systray, you can use `kwin rules` to hide it.  You can hide/unhide `Thunderbird` by middle-mouse clicking `nbiff`.  :)

**Comment by mercifulboss** [comment]
The way I envisioned it was it working in the same way that other mailclients work by constantly residing in the tray until called forth

**Comment by pablos-here** [comment]
> The way I envisioned it was it working in the same way that other mailclients work by constantly residing in the tray until called forth

Ah ha!  That's exactly it .... `nbiff` is not the mail client.  It's just a wee little helper app to make `Thunderbird`, the mail client`, play nice(r?) in Linux.  

btw, I developed it on KDE 5/X.   Once my rolling distro gets KDE 6, I'll be right behind you.  Thx for testing it out!

**Comment by mercifulboss** [comment]
> > The way I envisioned it was it working in the same way that other mailclients work by constantly residing in the tray until called forth
> 
> Ah ha! That's exactly it .... `nbiff` is not the mail client. It's just a wee little helper app to make `Thunderbird`, the mail client`, play nice(r?) in Linux.
> 
> btw, I developed it on KDE 5/X. Once my rolling distro gets KDE 6, I'll be right behind you. Thx for testing it out!

Ah I see. I was looking for something that would put thunderbird into the tray, since that option didn't exist on linux and would autostart on launch (without having the program in the taskbar)

**Comment by pablos-here** [comment]
> Ah I see. I was looking for something that would put thunderbird into the tray, since that option didn't exist on linux and would autostart on launch (without having the program in the taskbar)

Assuming that you have `Thunderbird` set to auto start, to emulate hiding it in `nbiff`, hide it from being displayed in the systray.  This is done using a `kwin rule` - see https://userbase.kde.org/KWin_Rules
